version: '3'

services: 

  jumpaku-othello:
    build: ./
    container_name: 'jumpaku-othello'
    networks: 
      - 'reverse_proxy_network'
    ports:
      - '8080:8080'

networks:
  reverse_proxy_network:
    external: true